# Generated by Django 4.1.5 on 2023-02-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_choice_text_alter_question_question_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.choice')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='question', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Assesment',
        ),
        migrations.AddField(
            model_name='choiceselection',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
        ),
        migrations.AddField(
            model_name='choiceselection',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.submission'),
        ),
    ]
