# Generated by Django 4.1.5 on 2023-02-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_rename_text_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='course',
            new_name='question',
        ),
    ]
