# Generated by Django 4.1.5 on 2023-02-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_choice_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceselection',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='onlinecourse.submission'),
        ),
    ]
